apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.cache.yml
    kompose.version: 1.34.0 (cbf2835db)
  creationTimestamp: "2024-12-03T07:15:16Z"
  generateName: cache-server-69cd6796c8-
  labels:
    io.kompose.service: cache-server
    pod-template-hash: 69cd6796c8
  name: cache-server-69cd6796c8-stffm
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: cache-server-69cd6796c8
      uid: 0d9a5c17-eace-4694-bfe8-5ad7227d4284
  resourceVersion: "285978"
  uid: 8fb89d23-0350-4a05-8634-603f50a590e6
spec:
  containers:
    - env:
        - name: API_BASE_URL
          value: http://localhost:3000
        - name: URL_ACCESS_TOKEN
          value: "123"
      image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
      imagePullPolicy: Always
      name: cache-server
      ports:
        - containerPort: 3000
          protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /app/.data
          name: cache-data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-lvpvh
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: cache-data
      persistentVolumeClaim:
        claimName: cache-data
    - name: kube-api-access-lvpvh
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-12-03T10:34:02Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2024-12-03T07:15:18Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-12-03T10:34:02Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-12-03T10:34:02Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-12-03T07:15:18Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: docker://b88ba98c32d2fef30cac1bb65f61554f013cb49e157df5468d78f6b0abc349e6
      image: ghcr.io/falcondev-oss/github-actions-cache-server:latest
      imageID: docker-pullable://ghcr.io/falcondev-oss/github-actions-cache-server@sha256:5d30c354b09e08186baab24fa13063435cf4104b5f5a3a90401cc5a62688e82a
      lastState:
        terminated:
          containerID: docker://6dac5dc5aa49ce9ff2596f665283d04067d8e6a294eb6b0aafbe8377b56e88d2
          exitCode: 0
          finishedAt: "2024-12-03T10:33:34Z"
          reason: Completed
          startedAt: "2024-12-03T07:15:31Z"
      name: cache-server
      ready: true
      restartCount: 1
      started: true
      state:
        running:
          startedAt: "2024-12-03T10:34:02Z"
      volumeMounts:
        - mountPath: /app/.data
          name: cache-data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-lvpvh
          readOnly: true
          recursiveReadOnly: Disabled
  hostIP: 192.168.112.2
  hostIPs:
    - ip: 192.168.112.2
  phase: Running
  podIP: 10.244.14.96
  podIPs:
    - ip: 10.244.14.96
  qosClass: BestEffort
  startTime: "2024-12-03T07:15:18Z"
