name: Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-set

    steps:
    - name: docker
      run: docker --version
    - name: docker-service
      run: systemctl status docker
