name: Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-cached

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: docker
        run: docker --version
      - name: docker-service
        run: |
          docker build .
